# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cfc6b27bb01e996f52581925c3f66142704f23aa5598eaf5ea7abcf61759c001219a18329c4064154e54c62e5b0188302e05688082a1c971a3c2c909c1c9fc4

test:
  secret_key_base: e511c4021fb75d866da026b6d0dace6f682530347433a0798cd0d3ed8a8970ae9399e0aa4f98fd26e0bc2d1fed5fd3042b85f193c1e9225785545330e1fdd17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
